lib/bird_song_web/router.ex
defmodule BirdSongWeb.Router do
  use BirdSongWeb, :router

  import BirdSongWeb.UserAuth,
    only: [
      fetch_current_user: 2,
      guardian_fetch_current_user: 2,
      require_authenticated_user: 2,
      redirect_if_user_is_authenticated: 2
    ]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BirdSongWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_live_flash
    plug BirdSong.Accounts.Pipeline
  end

  pipeline :api_auth do
    plug Guardian.Plug.LoadResource, allow_blank: true
  end

  pipeline :api_require_user do
    plug Guardian.Plug.EnsureAuthenticated
    plug Guardian.Plug.LoadResource, allow_blank: false
    plug :guardian_fetch_current_user
    plug BirdSongWeb.Plugs.AssignServices
  end

  scope "/", BirdSongWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BirdSongWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: BirdSongWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", BirdSongWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", BirdSongWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", BirdSongWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/api/v1", BirdSongWeb.Api.V1, as: :api_v1 do
    pipe_through [:api, :api_auth]

    post "/users/log_in", UserSessionController, :create
  end

  scope "/api/v1", BirdSongWeb.Api.V1, as: :api_v1 do
    pipe_through [:api, :api_require_user]
    delete "/users/log_out", UserSessionController, :delete
    get "/regions", RegionController, :index
    get "/regions/:region_code/birds", RegionBirdsController, :index
    post "/quizzes", QuizController, :create
    get "/quizzes/:quiz_id/bird/:bird_id", QuizBirdController, :show

    post "/quizzes/:quiz_id/bird/:bird_id/answer",
         QuizAnswersController,
         :create

    get "/users/:user_id/quizzes/:quiz_id", UserQuizController, :show
  end
end

lib/bird_song_web/views/layout_view.ex
defmodule BirdSongWeb.LayoutView do
  use BirdSongWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

  def render_flash(conn, type) do
    case get_flash(conn, type) do
      nil -> ""
      flash -> content_tag(:p, [flash], class: ["alert", flash_error_class(type)], role: "alert")
    end
  end

  defp flash_error_class(:info), do: "alert-info"
  defp flash_error_class(:error), do: "alert-danger"
end

lib/bird_song_web/templates/layout/_user_menu.html.heex
<%= if @current_user do %>
  <li><span>Signed in as <%= @current_user.email %></span></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
  <li><%= link "Account Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
<% else %>
  <li><%= link "Create an account", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>

lib/bird_song_web/templates/layout/app.html.heex
<main class="container">
  <%= render_flash(@conn, :info) %>
  <%= render_flash(@conn, :error) %>
  <%= @inner_content %>
</main>

lib/bird_song_web/templates/layout/heading.html.heex
<header>
    <nav class="navbar bg-base-100 px-0">
      <h1 class="navbar-start flex-1 h2"><a href="/">BirdSong</a></h1>
      <div class="flex-none navbar-end">

        <label for="drawer-nav" class="drawer-button btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </label>
      </div>
    </nav>
</header>

lib/bird_song_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/bird_song_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "BirdSong", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>

      <div class="drawer drawer-end">
        <input id="drawer-nav" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content px-4 w-auto">
          <!-- Page content here -->
          <%= render("heading.html", conn: @conn) %>

          <%= @inner_content %>
        </div>
        <div class="drawer-side">
          <label for="drawer-nav" class="drawer-overlay"></label>
          <ul class="menu p-4 w-80 bg-base-100 text-base-content">
            <%= render "_user_menu.html", assigns %>
            <li><a href="/quiz/new">Start a new quiz</a></li>
            <li><a href="/about">About BirdSong</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </div>
      </div>
  </body>
</html>